// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.clubs */
export type ClubsId = number & { __brand: 'ClubsId' };

/** Represents the table public.clubs */
export default interface Clubs {
  id: ClubsId;

  club_name: string;
}

/** Represents the initializer for the table public.clubs */
export interface ClubsInitializer {
  /** Default value: nextval('clubs_id_seq'::regclass) */
  id?: ClubsId;

  club_name: string;
}

/** Represents the mutator for the table public.clubs */
export interface ClubsMutator {
  id?: ClubsId;

  club_name?: string;
}
