// @generated
// This file is automatically generated by Kanel. Do not modify manually.

/** Identifier type for public.competitions */
export type CompetitionsId = number & { __brand: 'CompetitionsId' };

/** Represents the table public.competitions */
export default interface Competitions {
  id: CompetitionsId;

  competition_name: string;
}

/** Represents the initializer for the table public.competitions */
export interface CompetitionsInitializer {
  /** Default value: nextval('competitions_id_seq'::regclass) */
  id?: CompetitionsId;

  competition_name: string;
}

/** Represents the mutator for the table public.competitions */
export interface CompetitionsMutator {
  id?: CompetitionsId;

  competition_name?: string;
}
