// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ClubsId } from './Clubs';

/** Identifier type for public.players */
export type PlayersId = number & { __brand: 'PlayersId' };

/** Represents the table public.players */
export default interface Players {
  id: PlayersId;

  player_name: string;

  player_surname: string;

  club_id: ClubsId;
}

/** Represents the initializer for the table public.players */
export interface PlayersInitializer {
  /** Default value: nextval('players_id_seq'::regclass) */
  id?: PlayersId;

  player_name: string;

  player_surname: string;

  club_id: ClubsId;
}

/** Represents the mutator for the table public.players */
export interface PlayersMutator {
  id?: PlayersId;

  player_name?: string;

  player_surname?: string;

  club_id?: ClubsId;
}
